version: '3.9'

services:
  db:
    image: postgres:latest
    env_file:
      - config.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: ["postgres", "-p", "${POSTGRES_PORT}"]
    volumes:
      - ./migration/migration.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data


  app:
    build: ./
    env_file:
      - config.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - logs:/logs/

volumes:
  db_data:
  logs:
